/*******************************************************************************
 * Copyright (c) 2011 Greg Riccardi, Guillaume Jimenez.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the GNU Public License v2.0
 *  which accompanies this distribution, and is available at
 *  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *  
 *  Contributors:
 *  	Greg Riccardi - initial API and implementation
 * 	Guillaume Jimenez - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.11 at 11:38:16 AM EST 
//


package net.morphbank.mbsvc3.xml;

import java.util.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "query", propOrder = {
    "submitter",
    "method",
    "format",
    "limit",
    "firstResult",
    "objectType",
    "queryString",
    "keywords",
    "taxonName",
    "id",
    "changeDate",
    "lastChangeDate",
    "numChangeDays",
    "geolocated",
    "isPublic",
    "isExact",
    "hostServer"
})
@XmlRootElement(name = "query")
public class Query {

    protected Credentials submitter;
    @XmlElement(required = true)
    protected String method;
    @XmlElement(required = true)
    protected String format;
    protected Integer limit;
    protected Integer firstResult;
    protected List<String> objectType;
    protected String queryString;
    protected String keywords;
    protected String taxonName;
    protected Integer id;
    protected Date changeDate;
    protected Date lastChangeDate;
    protected Integer numChangeDays;
    protected Boolean geolocated;
    protected Boolean isPublic;
    protected Boolean isExact;
    protected String hostServer;

    public String getFormat() {
        return format;
    }

     public void setFormat(String format) {
        this.format = format;
    }

     public Boolean getGeolocated() {
		return geolocated;
	}

	public void setGeolocated(Boolean geolocated) {
		this.geolocated = geolocated;
	}

	public String getQueryString() {
        return queryString;
    }

    public void setQueryString(String value) {
        this.queryString = value;
    }

     public List<String> getObjectType() {
        if (objectType == null) {
            objectType = new ArrayList<String>();
        }
        return this.objectType;
    }

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	public Integer getFirstResult() {
		return firstResult;
	}

	public void setFirstResult(Integer firstResult) {
		this.firstResult = firstResult;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getTaxonName() {
		return taxonName;
	}

	public void setTaxonName(String taxonName) {
		this.taxonName = taxonName;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setObjectType(List<String> objectType) {
		this.objectType = objectType;
	}
	
	public String[] getObjectTypes(){
		String [] objectTypes = new String[getObjectType().size()];
		for (int i = 0; i<objectTypes.length; i++){
			objectTypes[i] = getObjectType().get(i);
		}
		return objectTypes;
	}

	public Credentials getSubmitter() {
		return submitter;
	}

	public void setSubmitter(Credentials submitter) {
		this.submitter = submitter;
	}

	public String getMethod() {
		return method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Date getChangeDate() {
		return changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Date getLastChangeDate() {
		return lastChangeDate;
	}

	public void setLastChangeDate(Date lastChangeDate) {
		this.lastChangeDate = lastChangeDate;
	}

	public Integer getNumChangeDays() {
		return numChangeDays;
	}

	public void setNumChangeDays(Integer numChangeDays) {
		this.numChangeDays = numChangeDays;
	}

	public Boolean isPublic() {
		return isPublic;
	}

	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

	public Boolean isExact() {
		return isExact;
	}

	public void setIsExact(Boolean isExact) {
		this.isExact = isExact;
	}

	public String getHostServer() {
		return hostServer;
	}

	public void setHostServer(String hostServer) {
		this.hostServer = hostServer;
	}

}
