package net.morphbank.loadexcel;

/**
 * All column names should be changed 
 * or added here. 
 */
public class ExcelTools {


	
	//Image
	public static final String COL_IMAGE_FILE_NAME = "Image file name";
	public static final String COL_MAGNIFICATION = "Magnification";
	public static final String COL_COPYRIGHT_INFO = "Copyright Info";
	public static final String COL_MY_VIEW_NAME = "My View Name";
	public static final String COL_PHOTOGRAPHER = "Photographer";
	public static final String COL_CREATIVE_COMMONS = "Creative Commons";
	public static final String COL_EOL = "eol";
	public static final String COL_IMAGE_SPECIMEN_DESCRIPTION = "Specimen Description";
	
	//Locality
	public static final String COL_LOCALITY_NAME = "Locality Name [Auto generated--Do not change!]";
	public static final String COL_CONTINENT_OCEAN = "Continent Ocean";
	public static final String COL_CONTINENT = "Continent";
	public static final String COL_WATER_BODY = "Water Body";
	public static final String COL_COUNTRY = "Country";
	public static final String COL_LOCALITY_DESCRIPTION = "Locality Description";
	public static final String COL_LATITUDE = "Latitude";
	public static final String COL_LONGITUDE = "Longitude";
	public static final String COL_COORDINATE_PRECISION = "Coordinate Precision";
	public static final String COL_MINIMUM_ELEVATION = "Minimum Elevation";
	public static final String COL_MAXIMUM_ELEVATION = "Maximum Elevation";
	public static final String COL_MINIMUM_DEPTH = "Minimum Depth";
	public static final String COL_MAXIMUM_DEPTH = "Maximum Depth";
	public static final String COL_STATE_OR_PROVINCE = "State or Province";
	public static final String COL_COUNTY = "County";
	public static final String COL_INFORMATION_WITHHELD = "Information Withheld";
	//Specimen
	public static final String COL_SPECIMEN_DESCRIPTION = "Specimen Description [Autogenerated -- do not change!]";
	public static final String COL_SCIENTIFIC_NAME = "Scientific Name";
	public static final String COL_BASIS_OF_RECORD = "Basis of Record";
	public static final String COL_SEX = "Sex";
	public static final String COL_DEVELOPMENTAL_STAGE = "Developmental Stage";
	public static final String COL_FORM = "Form";
	public static final String COL_PREPARATION_TYPE = "Preparation Type";
	public static final String COL_NUMBER_OF_INDIVIDUALS = "Number of Individuals";
	public static final String COL_TYPE_STATUS = "Type Status";
	public static final String COL_DETERMINED_BY = "Determined By";
	public static final String COL_DATE_DETERMINED = "Date Determined";
	public static final String COL_DETERMINATION_NOTES = "Determination Notes";
	public static final String COL_INSTITUTION_CODE = "Institution Code";
	public static final String COL_COLLECTION_CODE = "Collection Code";
	public static final String COL_CATALOG_NUMBER = "Catalog Number";
	public static final String COL_PREVIOUS_CATALOG_NUMBER = "Previous Catalog Number";
	public static final String COL_RELATED_CATALOG_ITEM = "Related Catalog Item";
	public static final String COL_RELATIONSHIP_TYPE = "Relationship Type";
	public static final String COL_COLLECTION_NUMBER = "Collection Number";
	public static final String COL_COLLECTOR_NAME = "Collector(s) Name";
	public static final String COL_DATE_COLLECTED = "Date Collected";
	public static final String COL_EARLIEST_DATE_COLLECTED = "Earliest Date Collected";
	public static final String COL_LATEST_DATE_COLLECTED = "Latest Date Collected";
	public static final String COL_NOTES = "Notes";
	public static final String COL_LOCALITY = "Locality";
	//TaxonData
	public static final String COL_FAMILY = "Family";
	public static final String COL_GENUS = "Genus";
	public static final String COL_SUBGENUS = "Subgenus";
	public static final String COL_SPECIFIC_EPITHET = "Specific epithet";
	public static final String COL_SSP = "ssp.";
	public static final String COL_VAR = "var.";
	public static final String COL_FORMA = "forma";
	public static final String COL_SCIENTIFICNAMESTRING = "ScientificNameString";
	public static final String COL_TAXON_AUTHOR_YEAR = "Taxon Author(s),year (use if not in morphbank)";
	public static final String COL_MORPHBANK_PUBLICATION_ID = "Morphbank Publication Id";
	public static final String COL_PUBLICATION_PAGES = "Publication Pages";
	public static final String COL_TRADEDESIGNATIONNAMES = "TradeDesignationNames";
	public static final String COL_NOMENCLATURAL_CODE = "Nomenclatural Code";
	public static final String COL_NAME_SOURCE = "Name Source";
	public static final String COL_COMMENTS = "Comments";
	//View
	public static final String COL_SPECIMEN_PART = "Specimen Part";
	public static final String COL_VIEW_ANGLE = "View Angle";
	public static final String COL_IMAGING_TECHNIQUE = "Imaging Technique";
	public static final String COL_VIEW_APPLICABLE_TO_TAXON = "View Applicable to Taxon";	
	public static final String COL_IMAGING_PREPARATION_TECHNIQUE = "Imaging Preparation Technique";
	public static final String COL_VIEW_DEVELOPMENTAL_STAGE = "Developmental Stage";
	public static final String COL_VIEW_SEX = "Sex";
	public static final String COL_VIEW_FORM = "Form";	
	public static final String COL_MY_VIEW_NAME_AUTO = "My ViewName[ Auto generated, do not change this field!]";
	public static final String VIEW_APPLICABLE_TO_TAXON = "View Applicable to Taxon";
	
	//Sheets
	public static final String SPECIMEN_TAXON_DATA_SHEET = "SpecimenTaxonData";
	public static String SPECIMEN_SHEET = "Specimen";
	public static String LOCALITY_SHEET = "Locality";
	public static String IMAGE_SHEET = "Images";
	public static String VIEW_SHEET = "MyView";
	public static String SUPPORTING_DATA_SHEET = "SupportingData";
	public static String EXT_LINK_SHEET = "ExternalLinks";
	public static String IMAGE_COLLECTION_SHEET = "ImageCollection";
	public static String PROTECTED_DATA_SHEET = "ProtectedData";

	
	/**
	 * Append messages to a StringBuffer that can be used to
	 * display messages on a webpage.
	 * @param message
	 */
	public static void messageToOutput(String message, StringBuffer output) {
		output.append(message);
		output.append("<br />");
	}
	
}
