/*******************************************************************************
 * Copyright (c) 2011 Greg Riccardi, Guillaume Jimenez.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the GNU Public License v2.0
 *  which accompanies this distribution, and is available at
 *  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *  
 *  Contributors:
 *  	Greg Riccardi - initial API and implementation
 * 	Guillaume Jimenez - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 04:32:09 PM EST 
//


package net.morphbank.mbsvc3.morphster.rdf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.morphbank.rdf.morphster.m package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Comment_QNAME = new QName("http://www.w3.org/2000/01/rdf-schema#", "comment");
    private final static QName _Label_QNAME = new QName("http://www.w3.org/2000/01/rdf-schema#", "label");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.morphbank.rdf.morphster.m
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CharacterState }
     * 
     */
    public CharacterState createCharacterState() {
        return new CharacterState();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link AnatomicalEntity }
     * 
     */
    public AnatomicalEntity createAnatomicalEntity() {
        return new AnatomicalEntity();
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link ObjectProperty }
     * 
     */
    public ObjectProperty createObjectProperty() {
        return new ObjectProperty();
    }

    /**
     * Create an instance of {@link HasEntity }
     * 
     */
    public HasEntity createHasEntity() {
        return new HasEntity();
    }

    /**
     * Create an instance of {@link HasPart }
     * 
     */
    public HasPart createHasPart() {
        return new HasPart();
    }

    /**
     * Create an instance of {@link PhenotypicQuality }
     * 
     */
    public PhenotypicQuality createPhenotypicQuality() {
        return new PhenotypicQuality();
    }

    /**
     * Create an instance of {@link Ontology }
     * 
     */
    public Ontology createOntology() {
        return new Ontology();
    }

    /**
     * Create an instance of {@link Character }
     * 
     */
    public Character createCharacter() {
        return new Character();
    }

    /**
     * Create an instance of {@link AnnotatedOn }
     * 
     */
    public AnnotatedOn createAnnotatedOn() {
        return new AnnotatedOn();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link HasQuality }
     * 
     */
    public HasQuality createHasQuality() {
        return new HasQuality();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link RDF }
     * 
     */
    public RDF createRDF() {
        return new RDF();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/01/rdf-schema#", name = "comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/01/rdf-schema#", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

}
