/*******************************************************************************
 * Copyright (c) 2011 Greg Riccardi, Guillaume Jimenez.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the GNU Public License v2.0
 *  which accompanies this distribution, and is available at
 *  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *  
 *  Contributors:
 *  	Greg Riccardi - initial API and implementation
 * 	Guillaume Jimenez - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 03:18:17 PM EST 
//


package net.morphbank.mbsvc3.morphster.rdf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/2002/07/owl#}Ontology"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.w3.org/2002/07/owl#}Class"/>
 *           &lt;element ref="{http://www.w3.org/2002/07/owl#}ObjectProperty"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.cs.utexas.edu/~miranker/ontology/morphster.owl#}Image"/>
 *         &lt;element ref="{http://www.cs.utexas.edu/~miranker/ontology/morphster.owl#}CharacterState" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.cs.utexas.edu/~miranker/ontology/morphster.owl#}Character" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.cs.utexas.edu/~miranker/ontology/morphster.owl#}AnatomicalEntity" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.cs.utexas.edu/~miranker/ontology/morphster.owl#}PhenotypicQuality"/>
 *         &lt;element ref="{http://www.cs.utexas.edu/~miranker/ontology/morphster.owl#}Annotation" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"ontology",
		"clazzOrObjectProperty",
		"image",
		"characterState",
		"character",
		"anatomicalEntity",
		"phenotypicQuality",
		"annotation"
})
@XmlRootElement(name = "RDF", namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
public class RDF {

	@XmlElement(name = "Ontology", namespace = "http://www.w3.org/2002/07/owl#", required = true)
	protected Ontology ontology;
	@XmlElements({
		@XmlElement(name = "ObjectProperty", namespace = "http://www.w3.org/2002/07/owl#", type = ObjectProperty.class),
		@XmlElement(name = "Class", namespace = "http://www.w3.org/2002/07/owl#", type = Class.class)
	})
	protected List<Object> clazzOrObjectProperty;
	@XmlElement(name = "Image", required = true)
	protected Image image;
	@XmlElement(name = "CharacterState", required = true)
	protected List<CharacterState> characterState;
	@XmlElement(name = "Character", required = true)
	protected List<Character> character;
	@XmlElement(name = "AnatomicalEntity", required = true)
	protected List<AnatomicalEntity> anatomicalEntity;
	@XmlElement(name = "PhenotypicQuality", required = true)
	protected List<PhenotypicQuality> phenotypicQuality;
	@XmlElement(name = "Annotation", required = true)
	protected List<Annotation> annotation;
	@XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
	@XmlSchemaType(name = "anyURI")
	protected String base;

	/**
	 * Gets the value of the ontology property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Ontology }
	 *     
	 */
	public Ontology getOntology() {
		return ontology;
	}

	/**
	 * Sets the value of the ontology property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Ontology }
	 *     
	 */
	public void setOntology(Ontology value) {
		this.ontology = value;
	}

	/**
	 * Gets the value of the clazzOrObjectProperty property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the clazzOrObjectProperty property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getClazzOrObjectProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ObjectProperty }
	 * {@link Class }
	 * 
	 * 
	 */
	public List<Object> getClazzOrObjectProperty() {
		if (clazzOrObjectProperty == null) {
			clazzOrObjectProperty = new ArrayList<Object>();
		}
		return this.clazzOrObjectProperty;
	}

	/**
	 * Gets the value of the image property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Image }
	 *     
	 */
	public Image getImage() {
		return image;
	}

	/**
	 * Sets the value of the image property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Image }
	 *     
	 */
	public void setImage(Image value) {
		this.image = value;
	}

	/**
	 * Gets the value of the characterState property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the characterState property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getCharacterState().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CharacterState }
	 * 
	 * 
	 */
	public List<CharacterState> getCharacterState() {
		if (characterState == null) {
			characterState = new ArrayList<CharacterState>();
		}
		return this.characterState;
	}

	/**
	 * Gets the value of the character property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the character property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getCharacter().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Character }
	 * 
	 * 
	 */
	public List<Character> getCharacter() {
		if (character == null) {
			character = new ArrayList<Character>();
		}
		return this.character;
	}

	/**
	 * Gets the value of the anatomicalEntity property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the anatomicalEntity property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getAnatomicalEntity().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AnatomicalEntity }
	 * 
	 * 
	 */
	public List<AnatomicalEntity> getAnatomicalEntity() {
		if (anatomicalEntity == null) {
			anatomicalEntity = new ArrayList<AnatomicalEntity>();
		}
		return this.anatomicalEntity;
	}

	/**
	 * Gets the value of the phenotypicQuality property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link PhenotypicQuality }
	 *     
	 */
	public List<PhenotypicQuality> getPhenotypicQuality() {
		if (phenotypicQuality == null) {
			phenotypicQuality = new ArrayList<PhenotypicQuality>();
		}
		return phenotypicQuality;
	}



	/**
	 * Gets the value of the annotation property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the annotation property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getAnnotation().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Annotation }
	 * 
	 * 
	 */
	public List<Annotation> getAnnotation() {
		if (annotation == null) {
			annotation = new ArrayList<Annotation>();
		}
		return this.annotation;
	}

	/**
	 * Gets the value of the base property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getBase() {
		return base;
	}

	/**
	 * Sets the value of the base property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setBase(String value) {
		this.base = value;
	}
}
