/*******************************************************************************
 * Copyright (c) 2011 Greg Riccardi, Guillaume Jimenez.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the GNU Public License v2.0
 *  which accompanies this distribution, and is available at
 *  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *  
 *  Contributors:
 *  	Greg Riccardi - initial API and implementation
 * 	Guillaume Jimenez - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.11 at 11:38:16 AM EST 
//

package net.morphbank.mbsvc3.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credentials", propOrder = { "keyString", "userId", "uin", "groupId", "groupName",
		"password", "userName" })
public class Credentials {

	protected String keyString;
	protected Integer userId;
	protected Integer groupId;
	protected String uin;
	protected String groupName;
	protected String password;
	protected String userName;

	public Credentials() {
		userId = 0;
		groupId = 0;
	}

	public Credentials(int userId, int groupId) {
		this.userId = userId;
		this.groupId = groupId;
	}

	public Credentials(int userId, int groupId, String password) {
		this(userId, groupId);
		this.password = password;
	}

	public Credentials(int id, String uin, int groupId, String groupName) {
		this.userId = id;
		this.uin = uin;
		this.groupId = groupId;
		this.groupName = groupName;
	}

	public Credentials(String uin, String groupName) {
		this.uin = uin;
		this.groupName = groupName;
	}

	public Credentials(int id, String uin) {
		// TODO Auto-generated constructor stub
		this.userId = id;
		this.uin = uin;
	}

	public String getKeyString() {
		return keyString;
	}

	public void setKeyString(String keyString) {
		this.keyString = keyString;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String value) {
		this.password = value;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		if (userId != null) {
			this.userId = userId;
		} else {
			this.userId = 0;
		}
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		if (groupId != null) {
			this.groupId = groupId;
		} else {
			this.groupId = 0;
		}
	}

	public String getUin() {
		return uin;
	}

	public void setUin(String uin) {
		this.uin = uin;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
