/*******************************************************************************
 * Copyright (c) 2011 Greg Riccardi, Guillaume Jimenez.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the GNU Public License v2.0
 *  which accompanies this distribution, and is available at
 *  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *  
 *  Contributors:
 *  	Greg Riccardi - initial API and implementation
 * 	Guillaume Jimenez - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.02.11 at 11:38:16 AM EST
//


@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.morphbank.net/mbsvc3/",
	xmlns = {
        @XmlNs(prefix="mb", namespaceURI="http://www.morphbank.net/mbsvc3/"),
        @XmlNs(prefix="dwc", namespaceURI="http://rs.tdwg.org/dwc/dwcore/"),
        @XmlNs(prefix="dwcg", namespaceURI="http://rs.tdwg.org/dwc/geospatial/"),
        @XmlNs(prefix="dwcc", namespaceURI="http://rs.tdwg.org/dwc/curatorial/"),
        @XmlNs(prefix="dwce", namespaceURI="http://rs.tdwg.org/dwc/dwelement/")
    }
	)
package net.morphbank.mbsvc3.xml;

import javax.xml.bind.annotation.*;


