/*******************************************************************************
 * Copyright (c) 2011 Greg Riccardi, Guillaume Jimenez.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the GNU Public License v2.0
 *  which accompanies this distribution, and is available at
 *  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *  
 *  Contributors:
 *  	Greg Riccardi - initial API and implementation
 * 	Guillaume Jimenez - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.11 at 11:38:16 AM EST 
//

package net.morphbank.mbsvc3.xml;

import javax.xml.bind.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.*;
import javax.xml.namespace.QName;
import java.util.*;
import java.text.*;
//import javax.xml.datatype.XMLGregorianCalendar;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the net.morphbank.mbservices package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	public final static QName _GeoreferenceSources_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "GeoreferenceSources");
	public final static QName _IdentifiedBy_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "IdentifiedBy");
	public final static QName _IdentificationQualifier_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "IdentificationQualifier");
	public final static QName _InfraspecificRank_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "InfraspecificRank");
	public final static QName _BasisOfRecord_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "BasisOfRecord");
	public final static QName _VerbatimCollectingDate_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "VerbatimCollectingDate");
	public final static QName _CoordinateUncertaintyInMeters_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/",
			"CoordinateUncertaintyInMeters");
	public final static QName _InstitutionCode_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "InstitutionCode");
	public final static QName _CollectingMethod_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "CollectingMethod");
	public final static QName _MinimumElevationInMeters_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "MinimumElevationInMeters");
	public final static QName _StateProvince_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "StateProvince");
	public final static QName _GeoreferenceRemarks_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "GeoreferenceRemarks");
	public final static QName _Preparations_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "Preparations");
	public final static QName _AuthorYearOfScientificName_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "AuthorYearOfScientificName");
	public final static QName _VerbatimLatitude_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "VerbatimLatitude");
	public final static QName _GeoreferenceProtocol_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "GeoreferenceProtocol");
	public final static QName _FootprintSpatialFit_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "FootprintSpatialFit");
	public final static QName _Island_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Island");
	public final static QName _MaximumElevationInMeters_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "MaximumElevationInMeters");
	public final static QName _Disposition_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "Disposition");
	public final static QName _Order_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Order");
	public final static QName _Remarks_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Remarks");
	public final static QName _WaterBody_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "WaterBody");
	public final static QName _County_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "County");
	public final static QName _ValidDistributionFlag_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "ValidDistributionFlag");
	public final static QName _LifeStage_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "LifeStage");
	public final static QName _Family_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Family");
	public final static QName _DateIdentified_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "DateIdentified");
	public final static QName _FootprintWKT_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "FootprintWKT");
	public final static QName _Collector_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Collector");
	public final static QName _SpecificEpithet_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "SpecificEpithet");
	public final static QName _OtherCatalogNumbers_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "OtherCatalogNumbers");
	public final static QName _MinimumDepthInMeters_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "MinimumDepthInMeters");
	public final static QName _Phylum_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Phylum");
	public final static QName _VerbatimElevation_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "VerbatimElevation");
	public final static QName _CatalogNumber_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "CatalogNumber");
	public final static QName _VerbatimDepth_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "VerbatimDepth");
	public final static QName _Locality_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Locality");
	public final static QName _DecimalLongitude_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "DecimalLongitude");
	public final static QName _DateLastModified_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "DateLastModified");
	public final static QName _GenBankNumber_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "GenBankNumber");
	public final static QName _IndividualCount_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "IndividualCount");
	public final static QName _VerbatimCoordinates_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "VerbatimCoordinates");
	public final static QName _CollectionCode_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "CollectionCode");
	public final static QName _CatalogNumberNumeric_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "CatalogNumberNumeric");
	public final static QName _Sex_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Sex");
	public final static QName _Kingdom_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Kingdom");
	public final static QName _HigherTaxon_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "HigherTaxon");
	public final static QName _VerbatimCoordinateSystem_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "VerbatimCoordinateSystem");
	public final static QName _Continent_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Continent");
	public final static QName _InfraspecificEpithet_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "InfraspecificEpithet");
	public final static QName _IslandGroup_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "IslandGroup");
	public final static QName _DwElement_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwelement", "dwElement");
	public final static QName _CollectorNumber_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "CollectorNumber");
	public final static QName _MaximumDepthInMeters_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "MaximumDepthInMeters");
	public final static QName _ImageURL_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "ImageURL");
	public final static QName _Attributes_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Attributes");
	public final static QName _DecimalLatitude_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "DecimalLatitude");
	public final static QName _InformationWithheld_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "InformationWithheld");
	public final static QName _NomenclaturalCode_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "NomenclaturalCode");
	public final static QName _RelatedInformation_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "RelatedInformation");
	public final static QName _ScientificName_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "ScientificName");
	public final static QName _Class_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Class");
	public final static QName _GeodeticDatum_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "GeodeticDatum");
	public final static QName _HigherGeography_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "HigherGeography");
	public final static QName _Genus_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Genus");
	public final static QName _EarliestDateCollected_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "EarliestDateCollected");
	public final static QName _RelatedCatalogedItems_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "RelatedCatalogedItems");
	public final static QName _VerbatimLongitude_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "VerbatimLongitude");
	public final static QName _TypeStatus_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "TypeStatus");
	public final static QName _DayOfYear_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "DayOfYear");
	public final static QName _PointRadiusSpatialFit_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/", "PointRadiusSpatialFit");
	public final static QName _LatestDateCollected_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "LatestDateCollected");
	public final static QName _Country_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "Country");
	public final static QName _GlobalUniqueIdentifier_QNAME = new QName(
			"http://rs.tdwg.org/dwc/dwcore/", "GlobalUniqueIdentifier");
	public final static QName _FieldNotes_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "FieldNotes");
	public final static QName _GeoreferenceVerificationStatus_QNAME = new QName(
			"http://rs.tdwg.org/dwc/geospatial/",
			"GeoreferenceVerificationStatus");
	public final static QName _FieldNumber_QNAME = new QName(
			"http://rs.tdwg.org/dwc/curatorial/", "FieldNumber");
	public final static QName _RelationshipType = new QName(
			"http://digir.net/schema/conceptual/darwin/2003/1.0/", "RelationshipType"); //TODO is the URI correct here?
	

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: net.morphbank.mbservices
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Request }
	 * 
	 */
	public Request createRequest() {
		return new Request();
	}


	/**
	 * Create an instance of {@link Insert }
	 * 
	 */
	public Insert createInsert() {
		return new Insert();
	}

	/**
	 * Create an instance of {@link XmlId }
	 * 
	 */
	public XmlId createXmlId() {
		return new XmlId();
	}

	/**
	 * Create an instance of {@link Responses }
	 * 
	 */
	public Responses createResponses() {
		return new Responses();
	}

	/**
	 * Create an instance of {@link Credentials }
	 * 
	 */
	public Credentials createCredentials() {
		return new Credentials();
	}

//	/**
//	 * Create an instance of {@link XmlBaseObject }
//	 * 
//	 */
	public XmlBaseObject createXmlObject() {
		return new XmlBaseObject();
	}

	/**
	 * Create an instance of {@link Query }
	 * 
	 */
	public Query createQuery() {
		return new Query();
	}

	/**
	 * Create an instance of {@link Update }
	 * 
	 */
	public Update createUpdate() {
		return new Update();
	}

	/**
	 * Create an instance of {@link Response }
	 * 
	 */
	public Response createResponse() {
		return new Response();
	}

	/**
	 * Create an instance of {@link RequestSummary }
	 * 
	 */
	public RequestSummary createRequestSummary() {
		return new RequestSummary();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "GeoreferenceSources", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createGeoreferenceSources(String value) {
		return new JAXBElement<String>(_GeoreferenceSources_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "IdentifiedBy", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createIdentifiedBy(String value) {
		return new JAXBElement<String>(_IdentifiedBy_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "IdentificationQualifier", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createIdentificationQualifier(String value) {
		return new JAXBElement<String>(_IdentificationQualifier_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "InfraspecificRank", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createInfraspecificRank(String value) {
		return new JAXBElement<String>(_InfraspecificRank_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "BasisOfRecord", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createBasisOfRecord(String value) {
		return new JAXBElement<String>(_BasisOfRecord_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "VerbatimCollectingDate", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createVerbatimCollectingDate(String value) {
		return new JAXBElement<String>(_VerbatimCollectingDate_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "CoordinateUncertaintyInMeters", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Integer> createCoordinateUncertaintyInMeters(
			Integer value) {
		return new JAXBElement<Integer>(_CoordinateUncertaintyInMeters_QNAME,
				Integer.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "InstitutionCode", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createInstitutionCode(String value) {
		return new JAXBElement<String>(_InstitutionCode_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "CollectingMethod", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createCollectingMethod(String value) {
		return new JAXBElement<String>(_CollectingMethod_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "MinimumElevationInMeters", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Double> createMinimumElevationInMeters(Double value) {
		return new JAXBElement<Double>(_MinimumElevationInMeters_QNAME,
				Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "StateProvince", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createStateProvince(String value) {
		return new JAXBElement<String>(_StateProvince_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "GeoreferenceRemarks", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createGeoreferenceRemarks(String value) {
		return new JAXBElement<String>(_GeoreferenceRemarks_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "Preparations", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createPreparations(String value) {
		return new JAXBElement<String>(_Preparations_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "AuthorYearOfScientificName", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createAuthorYearOfScientificName(String value) {
		return new JAXBElement<String>(_AuthorYearOfScientificName_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "VerbatimLatitude", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createVerbatimLatitude(String value) {
		return new JAXBElement<String>(_VerbatimLatitude_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "GeoreferenceProtocol", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createGeoreferenceProtocol(String value) {
		return new JAXBElement<String>(_GeoreferenceProtocol_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "FootprintSpatialFit", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createFootprintSpatialFit(String value) {
		return new JAXBElement<String>(_FootprintSpatialFit_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Island", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createIsland(String value) {
		return new JAXBElement<String>(_Island_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "MaximumElevationInMeters", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Double> createMaximumElevationInMeters(Double value) {
		return new JAXBElement<Double>(_MaximumElevationInMeters_QNAME,
				Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "Disposition", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createDisposition(String value) {
		return new JAXBElement<String>(_Disposition_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Order", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createOrder(String value) {
		return new JAXBElement<String>(_Order_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Remarks", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createRemarks(String value) {
		return new JAXBElement<String>(_Remarks_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "WaterBody", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createWaterBody(String value) {
		return new JAXBElement<String>(_WaterBody_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "County", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createCounty(String value) {
		return new JAXBElement<String>(_County_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "ValidDistributionFlag", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Boolean> createValidDistributionFlag(Boolean value) {
		return new JAXBElement<Boolean>(_ValidDistributionFlag_QNAME,
				Boolean.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "LifeStage", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createLifeStage(String value) {
		return new JAXBElement<String>(_LifeStage_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Family", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createFamily(String value) {
		return new JAXBElement<String>(_Family_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "DateIdentified", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Date> createDateIdentified(Date value) {
		return new JAXBElement<Date>(_DateIdentified_QNAME, Date.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "FootprintWKT", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createFootprintWKT(String value) {
		return new JAXBElement<String>(_FootprintWKT_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Collector", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createCollector(String value) {
		return new JAXBElement<String>(_Collector_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "SpecificEpithet", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createSpecificEpithet(String value) {
		return new JAXBElement<String>(_SpecificEpithet_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "OtherCatalogNumbers", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createOtherCatalogNumbers(String value) {
		return new JAXBElement<String>(_OtherCatalogNumbers_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "MinimumDepthInMeters", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Double> createMinimumDepthInMeters(Double value) {
		return new JAXBElement<Double>(_MinimumDepthInMeters_QNAME,
				Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Phylum", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createPhylum(String value) {
		return new JAXBElement<String>(_Phylum_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "VerbatimElevation", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createVerbatimElevation(String value) {
		return new JAXBElement<String>(_VerbatimElevation_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "CatalogNumber", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createCatalogNumber(String value) {
		return new JAXBElement<String>(_CatalogNumber_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "VerbatimDepth", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createVerbatimDepth(String value) {
		return new JAXBElement<String>(_VerbatimDepth_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Locality", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createLocality(String value) {
		return new JAXBElement<String>(_Locality_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "DecimalLongitude", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Double> createDecimalLongitude(Double value) {
		return new JAXBElement<Double>(_DecimalLongitude_QNAME, Double.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "DateLastModified", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Date> createDateLastModified(Date value) {
		return new JAXBElement<Date>(_DateLastModified_QNAME, Date.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "GenBankNumber", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createGenBankNumber(String value) {
		return new JAXBElement<String>(_GenBankNumber_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "IndividualCount", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Integer> createIndividualCount(Integer value) {
		return new JAXBElement<Integer>(_IndividualCount_QNAME, Integer.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "VerbatimCoordinates", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createVerbatimCoordinates(String value) {
		return new JAXBElement<String>(_VerbatimCoordinates_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "CollectionCode", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createCollectionCode(String value) {
		return new JAXBElement<String>(_CollectionCode_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "CatalogNumberNumeric", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Double> createCatalogNumberNumeric(Double value) {
		return new JAXBElement<Double>(_CatalogNumberNumeric_QNAME,
				Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Sex", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createSex(String value) {
		return new JAXBElement<String>(_Sex_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Kingdom", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createKingdom(String value) {
		return new JAXBElement<String>(_Kingdom_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "HigherTaxon", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createHigherTaxon(String value) {
		return new JAXBElement<String>(_HigherTaxon_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "VerbatimCoordinateSystem", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createVerbatimCoordinateSystem(String value) {
		return new JAXBElement<String>(_VerbatimCoordinateSystem_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Continent", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createContinent(String value) {
		return new JAXBElement<String>(_Continent_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "InfraspecificEpithet", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createInfraspecificEpithet(String value) {
		return new JAXBElement<String>(_InfraspecificEpithet_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "IslandGroup", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createIslandGroup(String value) {
		return new JAXBElement<String>(_IslandGroup_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwelement", name = "dwElement")
	public JAXBElement<Object> createDwElement(Object value) {
		return new JAXBElement<Object>(_DwElement_QNAME, Object.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "CollectorNumber", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createCollectorNumber(String value) {
		return new JAXBElement<String>(_CollectorNumber_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "MaximumDepthInMeters", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Double> createMaximumDepthInMeters(Double value) {
		return new JAXBElement<Double>(_MaximumDepthInMeters_QNAME,
				Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "ImageURL", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createImageURL(String value) {
		return new JAXBElement<String>(_ImageURL_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Attributes", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createAttributes(String value) {
		return new JAXBElement<String>(_Attributes_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "DecimalLatitude", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Double> createDecimalLatitude(Double value) {
		return new JAXBElement<Double>(_DecimalLatitude_QNAME, Double.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "InformationWithheld", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createInformationWithheld(String value) {
		return new JAXBElement<String>(_InformationWithheld_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "NomenclaturalCode", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createNomenclaturalCode(String value) {
		return new JAXBElement<String>(_NomenclaturalCode_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "RelatedInformation", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createRelatedInformation(String value) {
		return new JAXBElement<String>(_RelatedInformation_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "ScientificName", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createScientificName(String value) {
		return new JAXBElement<String>(_ScientificName_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Class", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createClass(String value) {
		return new JAXBElement<String>(_Class_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "GeodeticDatum", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createGeodeticDatum(String value) {
		return new JAXBElement<String>(_GeodeticDatum_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "HigherGeography", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createHigherGeography(String value) {
		return new JAXBElement<String>(_HigherGeography_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Genus", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createGenus(String value) {
		return new JAXBElement<String>(_Genus_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "EarliestDateCollected", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	//@XmlJavaTypeAdapter(DateTimeISO.class)
	public JAXBElement<Date> createEarliestDateCollected(Date value) {
		// Date day = value.
		return new JAXBElement<Date>(_EarliestDateCollected_QNAME, Date.class,
				null, value);
	}

	class DateTimeISO extends XmlAdapter<String, Date> {
		public DateTimeISO() {
		}

		DateFormat df = new SimpleDateFormat("yyyy-mm-dd");

		public Date unmarshal(String date) throws Exception {
			return df.parse(date.substring(0, 9));
		}

		public String marshal(Date date) throws Exception {
			return df.format(date);
		}
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "RelatedCatalogedItems", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createRelatedCatalogedItems(String value) {
		return new JAXBElement<String>(_RelatedCatalogedItems_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "VerbatimLongitude", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createVerbatimLongitude(String value) {
		return new JAXBElement<String>(_VerbatimLongitude_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "TypeStatus", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createTypeStatus(String value) {
		return new JAXBElement<String>(_TypeStatus_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "DayOfYear", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Integer> createDayOfYear(Integer value) {
		return new JAXBElement<Integer>(_DayOfYear_QNAME, Integer.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "PointRadiusSpatialFit", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createPointRadiusSpatialFit(String value) {
		return new JAXBElement<String>(_PointRadiusSpatialFit_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "LatestDateCollected", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<Date> createLatestDateCollected(Date value) {
		return new JAXBElement<Date>(_LatestDateCollected_QNAME,
				Date.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "Country", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createCountry(String value) {
		return new JAXBElement<String>(_Country_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/dwcore/", name = "GlobalUniqueIdentifier", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createGlobalUniqueIdentifier(String value) {
		return new JAXBElement<String>(_GlobalUniqueIdentifier_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "FieldNotes", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createFieldNotes(String value) {
		return new JAXBElement<String>(_FieldNotes_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/geospatial/", name = "GeoreferenceVerificationStatus", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createGeoreferenceVerificationStatus(String value) {
		return new JAXBElement<String>(_GeoreferenceVerificationStatus_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://rs.tdwg.org/dwc/curatorial/", name = "FieldNumber", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createFieldNumber(String value) {
		return new JAXBElement<String>(_FieldNumber_QNAME, String.class, null,
				value);
	}

	@XmlElementDecl(namespace = "http://digir.net/schema/conceptual/darwin/2003/1.0/", name = "RelationshipType", substitutionHeadNamespace = "http://rs.tdwg.org/dwc/dwelement", substitutionHeadName = "dwElement")
	public JAXBElement<String> createRelationshipType(String value) {
		return new JAXBElement<String>(_RelationshipType, String.class, value);
	}

}
