//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 09:14:12 AM EST 
//

package org.idiginfo.ipt.extension;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="property" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                 &lt;attribute name="namespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute name="qualName" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="columnLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="128" />
 *                 &lt;attribute name="type" type="{http://rs.gbif.org/extension/}dataType" default="string" />
 *                 &lt;attribute name="examples" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute ref="{http://purl.org/dc/terms/}relation"/>
 *                 &lt;attribute ref="{http://purl.org/dc/terms/}subject"/>
 *                 &lt;attribute ref="{http://purl.org/dc/terms/}description"/>
 *                 &lt;attribute name="thesaurus" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://purl.org/dc/terms/}title use="required""/>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="namespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="rowType" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute ref="{http://purl.org/dc/terms/}description"/>
 *       &lt;attribute ref="{http://purl.org/dc/terms/}relation"/>
 *       &lt;attribute ref="{http://purl.org/dc/terms/}subject"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "property" })
@XmlRootElement(name = "extension")
public class Extension {

	@XmlElement(required = true)
	protected List<Extension.Property> property;
	@XmlAttribute(name = "title", namespace = "http://purl.org/dc/terms/", required = true)
	protected String title;
	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String name;
	@XmlAttribute(name = "namespace", required = true)
	@XmlSchemaType(name = "anyURI")
	protected String namespace;
	@XmlAttribute(name = "rowType", required = true)
	@XmlSchemaType(name = "anyURI")
	protected String rowType;
	@XmlAttribute(name = "description", namespace = "http://purl.org/dc/terms/")
	protected String description;
	@XmlAttribute(name = "relation", namespace = "http://purl.org/dc/terms/")
	@XmlSchemaType(name = "anyURI")
	protected String relation;
	@XmlAttribute(name = "subject", namespace = "http://purl.org/dc/terms/")
	protected String subject;

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Extension.Property }
	 * 
	 * 
	 */
	public List<Extension.Property> getProperty() {
		if (property == null) {
			property = new ArrayList<Extension.Property>();
		}
		return this.property;
	}

	/**
	 * The human readable english title for the entire extension
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the namespace property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNamespace() {
		return namespace;
	}

	/**
	 * Sets the value of the namespace property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNamespace(String value) {
		this.namespace = value;
	}

	/**
	 * Gets the value of the rowType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowType() {
		return rowType;
	}

	/**
	 * Sets the value of the rowType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowType(String value) {
		this.rowType = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the relation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRelation() {
		return relation;
	}

	/**
	 * Sets the value of the relation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRelation(String value) {
		this.relation = value;
	}

	/**
	 * Gets the value of the subject property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * Sets the value of the subject property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubject(String value) {
		this.subject = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
	 *       &lt;attribute name="namespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
	 *       &lt;attribute name="qualName" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
	 *       &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="columnLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="128" />
	 *       &lt;attribute name="type" type="{http://rs.gbif.org/extension/}dataType" default="string" />
	 *       &lt;attribute name="examples" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute ref="{http://purl.org/dc/terms/}relation"/>
	 *       &lt;attribute ref="{http://purl.org/dc/terms/}subject"/>
	 *       &lt;attribute ref="{http://purl.org/dc/terms/}description"/>
	 *       &lt;attribute name="thesaurus" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
	 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	// @XmlType(propOrder = { "name", "required",
	// "description", "relation", "group", "qualName",
	// "namespace" })
	public static class Property {

		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NCName")
		protected String name;
		@XmlAttribute(name = "namespace", required = true)
		@XmlSchemaType(name = "anyURI")
		protected String namespace;
		@XmlAttribute(name = "qualName", required = true)
		@XmlSchemaType(name = "anyURI")
		protected String qualName;
		@XmlAttribute(name = "group")
		protected String group;
		@XmlAttribute(name = "columnLength")
		@XmlSchemaType(name = "positiveInteger")
		protected BigInteger columnLength;
		@XmlAttribute(name = "type")
		protected DataType type;
		@XmlAttribute(name = "examples")
		protected String examples;
		@XmlAttribute(name = "relation", namespace = "http://purl.org/dc/terms/")
		@XmlSchemaType(name = "anyURI")
		protected String relation;
		@XmlAttribute(name = "subject", namespace = "http://purl.org/dc/terms/")
		protected String subject;
		@XmlAttribute(name = "description", namespace = "http://purl.org/dc/terms/")
		protected String description;
		@XmlAttribute(name = "thesaurus")
		@XmlSchemaType(name = "anyURI")
		protected String thesaurus;
		@XmlAttribute(name = "required")
		protected Boolean required;

		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * Gets the value of the namespace property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNamespace() {
			return namespace;
		}

		/**
		 * Sets the value of the namespace property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNamespace(String value) {
			this.namespace = value;
		}

		/**
		 * Gets the value of the qualName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getQualName() {
			return qualName;
		}

		/**
		 * Sets the value of the qualName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setQualName(String value) {
			this.qualName = value;
		}

		/**
		 * Gets the value of the group property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getGroup() {
			return group;
		}

		/**
		 * Sets the value of the group property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setGroup(String value) {
			this.group = value;
		}

		/**
		 * Gets the value of the columnLength property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getColumnLength() {
			if (columnLength == null) {
				return new BigInteger("128");
			} else {
				return columnLength;
			}
		}

		/**
		 * Sets the value of the columnLength property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setColumnLength(BigInteger value) {
			this.columnLength = value;
		}

		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible object is {@link DataType }
		 * 
		 */
		public DataType getType() {
			if (type == null) {
				return DataType.STRING;
			} else {
				return type;
			}
		}

		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *            allowed object is {@link DataType }
		 * 
		 */
		public void setType(DataType value) {
			this.type = value;
		}

		/**
		 * Gets the value of the examples property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getExamples() {
			return examples;
		}

		/**
		 * Sets the value of the examples property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setExamples(String value) {
			this.examples = value;
		}

		/**
		 * Gets the value of the relation property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRelation() {
			return relation;
		}

		/**
		 * Sets the value of the relation property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRelation(String value) {
			this.relation = value;
		}

		/**
		 * Gets the value of the subject property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubject() {
			return subject;
		}

		/**
		 * Sets the value of the subject property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubject(String value) {
			this.subject = value;
		}

		/**
		 * Gets the value of the description property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescription() {
			return description;
		}

		/**
		 * Sets the value of the description property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDescription(String value) {
			this.description = value;
		}

		/**
		 * Gets the value of the thesaurus property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getThesaurus() {
			return thesaurus;
		}

		/**
		 * Sets the value of the thesaurus property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setThesaurus(String value) {
			this.thesaurus = value;
		}

		/**
		 * Gets the value of the required property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public boolean isRequired() {
			if (required == null) {
				return false;
			} else {
				return required;
			}
		}

		/**
		 * Sets the value of the required property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setRequired(Boolean value) {
			this.required = value;
		}

	}

}
